CREATE DATABASE node_felipe;

USE node_felipe;

CREATE TABLE grupoAcesso (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gp_name VARCHAR(10) NOT NULL
);

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE personagens (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    p_name VARCHAR(255) NOT NULL
);